#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    # MacOS
    ./run.sh
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Linux/Ubuntu
    ./run.sh
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ] || [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    # Windows
    run.bat
else
    echo "Unsupported OS"
    exit 1
fi
